-- AG-FlmOt.lua — Flameout Alarm: turbine flameout alarm from RPM telemetry, with an RPM bar window.
-- Copyright (c) 2026 Aaron George
-- SPDX-License-Identifier: MIT
--
-- Listen-and-inform only: it reads one RPM sensor and two switches, plays
-- sound, vibrates the sticks and draws. It never controls the model or the
-- engine (constitution principle I). The sounds in /Apps/AG-FlmOt/ are
-- licensed CC BY-SA 4.0 (Piper "Amy" voice), not MIT (FR-028).
--
-- Design: specs/003-flameout-alarm/ (plan.md, research.md, data-model.md,
-- contracts/). Research decisions are cited as R1..R13.

local APP_NAME = "Flameout Alarm"
local APP_VERSION = "0.1.0"
local AUDIO_DIR = "/Apps/AG-FlmOt/"
local TICK_MS = 100         -- logic runs at most 10x per second (R8)
local CYCLE_MS = 5000       -- one alarm cycle, callout start to callout start (FR-023)
-- The JETI Studio emulator draws each window's title bar inside the reported
-- canvas (157 x 127 / 157 x 60, ~26 px hidden); the transmitter draws it
-- above and reports 150 x 68 / 150 x 23 (Speed Gauge, 2026-10-03).
local TITLE_H = 26

-- Sound files, generated by tools/voice/make_flameout.py (R5).
local SND = {
  cycle = AUDIO_DIR .. "cycle.wav",       -- "Flameout!" x3 + lock tone, 5.000 s
  cycletl = AUDIO_DIR .. "cycletl.wav",   -- the same with "Engine telemetry lost"
  tlost = AUDIO_DIR .. "tlost.wav",
  armed = AUDIO_DIR .. "armed.wav",
  relit = AUDIO_DIR .. "relit.wav",
}

-- Engine monitor states (data-model.md).
local S = { OFF = 0, DISARMED = 1, ARMED = 2, FLAMEOUT = 3 }

local TXT = {
  off = "OFF", noSensor = "NO SENSOR", noTel = "NO TELEMETRY", disarmed = "DISARMED",
  armed = "ARMED", flameout = "FLAMEOUT", test = "TEST", noData = "---",
}

-- Debug switches, both off for release (R11, R12).
local DEBUG_CPU = false     -- show per-call CPU on the double-size window
local SIM = false           -- replace the RPM sensor with scripted profiles

------------------------------------------------------------------------------
-- Settings (persisted per model; data-model.md). Integers, one string and
-- SwitchItems only; booleans as 0/1, times in 0.1 s, RPM in hundreds
-- (constitution IV).
------------------------------------------------------------------------------

local KEYS = {
  "en", "sId", "sPar", "sLbl", "scl", "swCut", "idle", "maxR", "armP", "flP",
  "armT", "detT", "lossT", "sayArm", "sayRel", "swTest", "cfgV",
}  -- 17 keys (limit 30)
local DEFAULTS = {
  en = 0, sId = 0, sPar = 0, sLbl = "", scl = 1, idle = 0, maxR = 0, armP = 90,
  flP = 70, armT = 30, detT = 10, lossT = 20, sayArm = 0, sayRel = 0, cfgV = 1,
}  -- swCut and swTest default to nil
local RANGES = {
  en = { 0, 1 }, scl = { 1, 4 }, idle = { 0, 1500 }, maxR = { 0, 3000 },
  armP = { 50, 98 }, flP = { 20, 95 }, armT = { 10, 100 }, detT = { 3, 50 },
  lossT = { 5, 100 }, sayArm = { 0, 1 }, sayRel = { 0, 1 },
}
local SCALES = { 1, 10, 100, 1000 }   -- sensor scale x1 .. x1000 (FR-006a)

local cfg = {}

local function save(key, value)
  cfg[key] = value
  system.pSave(key, value)
end

local function clamp(v, lo, hi)
  if v < lo then
    return lo
  elseif v > hi then
    return hi
  end
  return v
end

local function loadSettings()
  for _, key in ipairs(KEYS) do
    cfg[key] = system.pLoad(key, DEFAULTS[key])
  end
  for key, r in pairs(RANGES) do
    local v = clamp(cfg[key], r[1], r[2])
    if v ~= cfg[key] then
      save(key, v)
    end
  end
  -- Combinations the form never allows (data-model.md "Validation").
  if cfg.flP >= cfg.armP then
    save("armP", DEFAULTS.armP)
    save("flP", DEFAULTS.flP)
  end
  if cfg.maxR ~= 0 and cfg.maxR <= cfg.idle then
    save("maxR", 0)
  end
  if cfg.en == 1 and (cfg.sId == 0 or cfg.swCut == nil or cfg.idle == 0) then
    save("en", 0)
  end
end

------------------------------------------------------------------------------
-- Derived values: recomputed only when a setting changes, never per tick.
------------------------------------------------------------------------------

local d = {
  active = false,           -- monitoring on and fully configured (FR-003, FR-012)
  kScale = 1,               -- sensor value -> RPM
  idleRpm = 0, armRpm = 0, flRpm = 0, fullRpm = 1,
  armMs = 3000, detMs = 1000, lossMs = 2000,
}

local function recompute()
  d.active = cfg.en == 1 and cfg.sId ~= 0 and cfg.swCut ~= nil and cfg.idle > 0
  d.kScale = SCALES[cfg.scl]
  d.idleRpm = cfg.idle * 100
  d.armRpm = d.idleRpm * cfg.armP // 100
  d.flRpm = d.idleRpm * cfg.flP // 100
  if cfg.maxR ~= 0 then
    d.fullRpm = cfg.maxR * 100
  else
    d.fullRpm = math.max(1, 4 * d.idleRpm)
  end
  d.armMs = cfg.armT * 100
  d.detMs = cfg.detT * 100
  d.lossMs = cfg.lossT * 100
end

------------------------------------------------------------------------------
-- Session state (not persisted; reset by init on every model load).
------------------------------------------------------------------------------

local st = {}

local function resetSession()
  st.state = d.active and S.DISARMED or S.OFF
  st.rpm = nil              -- last valid RPM; nil while invalid
  st.sensorFound = true     -- false: the sensor isn't in the model's list (FR-022)
  st.invalidSince = nil
  st.lost = false           -- invalid for at least lossMs (NO TELEMETRY)
  st.armSince = nil         -- RPM >= armRpm since (DISARMED, FLAMEOUT)
  st.lowSince = nil         -- RPM < flRpm since (ARMED)
  st.cycleAt = 0            -- start of the current alarm cycle
  st.beepAt = nil           -- second fallback beep burst due (R6)
  st.tlPending = false      -- play cycletl.wav at the next cycle (R4)
  st.testOn = false         -- a test alarm is playing (R13)
  st.testPrev = true        -- a test switch already on at load needs a toggle
  st.rpmText = TXT.noData
  st.rpmHundreds = -1
  st.lastTick = system.getTimeCounter()
  st.liveAt = 0             -- last Live RPM row update (form open only)
end

------------------------------------------------------------------------------
-- Audio (contracts/audio-events.md)
------------------------------------------------------------------------------

-- Which files exist, checked once in init() (R6).
local audio = { ok = false, tlost = false, armed = false, relit = false }

-- Jeti's io is function-style (constitution III). The transmitter opens
-- "/Apps/..."; the JETI Studio emulator (6.04) only opens the same path
-- without the leading "/" (2026-10-05), so try that too. Only this check
-- uses it: playback keeps the absolute path.
local function fileExists(path)
  local f = io.open(path, "r") or io.open(string.sub(path, 2), "r")
  if f then
    io.close(f)
    return true
  end
  return false
end

local function checkAudio()
  audio.ok = fileExists(SND.cycle) and fileExists(SND.cycletl)
  audio.tlost = fileExists(SND.tlost)
  audio.armed = fileExists(SND.armed)
  audio.relit = fileExists(SND.relit)
end

-- Starts one alarm cycle (R2, R6, R7). AUDIO_IMMEDIATE stops any other
-- foreground playback, so the alarm pre-empts other apps' speech (FR-025).
-- Without the cycle files: two bursts of beeps, the second 2.5 s later.
local function playCycle(now, file)
  if audio.ok then
    system.playFile(file, AUDIO_IMMEDIATE)
  else
    system.playBeep(9, 1800, 120)
    st.beepAt = now + 2500
  end
  system.vibration(false, 4)
  system.vibration(true, 4)
end

-- Stops alarm sound at once, mid-callout or mid-beep (R3).
local function stopAlarm()
  system.stopPlayback(AUDIO_IMMEDIATE)
  st.beepAt = nil
  st.tlPending = false
end

------------------------------------------------------------------------------
-- Engine monitor (data-model.md "State transitions"). One function per row
-- group; each user story fills its own.
------------------------------------------------------------------------------

-- SIM (debug, R12): scripted RPM profiles in place of the sensor, chosen in
-- the form while SIM is true. Each profile is a flat list of time (ms from
-- selection), RPM pairs, linearly interpolated; RPM -1 means invalid data.
-- The last value holds after the end.
local sim = { idx = 1, t0 = 0, out = { value = 0, valid = true } }
sim.names = { "Off (real sensor)", "Normal flight", "Failed start", "Flameout", "Auto-restart", "Dropouts" }
sim.profiles = {           -- sim.names[i + 1]
  { 0, 0, 5000, 0, 25000, 20000, 28000, 45000, 36000, 35000, 60000, 35000, 65000, 120000,
    90000, 120000, 92000, 35000, 100000, 35000, 103000, 120000, 130000, 120000,
    132000, 35000, 160000, 35000 },
  { 0, 0, 5000, 0, 20000, 25000, 23000, 25000, 30000, 0 },
  { 0, 0, 3000, 0, 15000, 40000, 20000, 60000, 40000, 60000, 43000, 0 },
  { 0, 60000, 8000, 60000, 11000, 0, 16000, 0, 20000, 10000, 24000, 28000, 27000, 8000,
    30000, 8000, 34000, 20000, 38000, 45000, 46000, 35000 },
  { 0, 35000, 10000, 35000, 10001, -1, 10500, -1, 10501, 35000, 15000, 35000, 15001, -1,
    18000, -1, 18001, 35000 },
}

local function simRead(now)
  local p = sim.profiles[sim.idx - 1]
  local t = now - sim.t0
  local v = p[#p]
  for i = 1, #p - 2, 2 do
    if t < p[i + 2] then
      local a, b = p[i + 1], p[i + 3]
      if a < 0 or b < 0 then
        v = -1
      else
        v = a + (b - a) * (t - p[i]) / (p[i + 2] - p[i])
      end
      break
    end
  end
  sim.out.valid = v >= 0
  sim.out.value = v
  return sim.out
end

-- Unassigned switch = off. "On" is above half travel (R10).
local function switchOn(item)
  if item == nil then
    return false
  end
  local v = system.getInputsVal(item)
  return v ~= nil and v > 0.5
end

local function stepTest(now)            -- test alarm, rows T1-T3 (US8)
end

-- Row 1 (FR-016): Cut disarms at once and silently from any state. Arming
-- again needs the switch out of Cut and row 3 (User Story 5).
local function onCut()
  if st.state == S.FLAMEOUT then
    stopAlarm()
  end
  st.state = S.DISARMED
  st.armSince, st.lowSince, st.invalidSince = nil, nil, nil
  st.tlPending, st.lost = false, false
end

local function onInvalid(now)           -- row 2 (US6)
end

-- Row 3 (FR-014): arms once RPM has held the arming threshold for the
-- arming time. The start overshoot above idle counts like any RPM above it.
local function stepDisarmed(now)
  if st.rpm >= d.armRpm then
    st.armSince = st.armSince or now
    if now - st.armSince >= d.armMs then
      st.state = S.ARMED
      st.armSince, st.lowSince = nil, nil
      if cfg.sayArm == 1 and audio.armed then
        system.playFile(SND.armed, AUDIO_QUEUE)   -- FR-009; queued, never cuts a callout
      end
    end
  else
    st.armSince = nil
  end
end

-- Row 4 (FR-015): RPM below the flameout threshold for the detection delay.
local function stepArmed(now)
  if st.rpm < d.flRpm then
    st.lowSince = st.lowSince or now
    if now - st.lowSince >= d.detMs then
      st.state = S.FLAMEOUT
      st.lowSince, st.armSince = nil, nil
      st.cycleAt = now
      playCycle(now, SND.cycle)
    end
  else
    st.lowSince = nil
  end
end

-- Row 5 (FR-017, FR-018): the alarm clears only when RPM holds the arming
-- threshold for the arming time, usually during the relight overshoot.
-- RPM in the startup range (an auto-restart cranking) breaks the timer and
-- starts nothing new; the same alarm continues.
local function stepFlameout(now)
  if st.rpm >= d.armRpm then
    st.armSince = st.armSince or now
    if now - st.armSince >= d.armMs then
      stopAlarm()
      st.state = S.ARMED
      st.armSince, st.lowSince = nil, nil
      if cfg.sayRel == 1 and audio.relit then
        system.playFile(SND.relit, AUDIO_QUEUE)
      end
    end
  else
    st.armSince = nil
  end
end

-- Row 6 (SC-012): a new cycle every 5 s, plus the second fallback beep burst.
local function stepCycle(now)
  if st.beepAt and now >= st.beepAt then
    system.playBeep(9, 1800, 120)
    st.beepAt = nil
  end
  if now - st.cycleAt >= CYCLE_MS then
    st.cycleAt = st.cycleAt + CYCLE_MS
    if now - st.cycleAt >= CYCLE_MS then
      st.cycleAt = now          -- fell more than a cycle behind: restart the rhythm
    end
    playCycle(now, SND.cycle)
  end
end

-- Whole RPM with a thousands separator: 112400 -> "112,400".
local function fmtRpm(r)
  if r >= 1000 then
    return string.format("%d,%03d", r // 1000, r % 1000)
  end
  return tostring(r)
end

-- "112,400" for the window, rebuilt only when RPM / 100 changes.
local function updateRpmText()
  local h = -1
  if st.rpm ~= nil then
    h = math.floor(st.rpm / 100 + 0.5)
  end
  if h == st.rpmHundreds then
    return
  end
  st.rpmHundreds = h
  if h < 0 then
    st.rpmText = TXT.noData
  else
    st.rpmText = fmtRpm(h * 100)
  end
end

------------------------------------------------------------------------------
-- Settings form (contracts/settings-form.md)
------------------------------------------------------------------------------

local sensorLabels, sensorIds, sensorPars, sensorUnits = {}, {}, {}, {}
local notFoundIdx = 0
local formOpen = false      -- loop may touch form rows only while true (R10)
local idx = {}              -- component indices of rows updated after creation

local LABEL_W = 210

local function heading(text)
  form.addRow(1)
  form.addLabel({ label = text, font = FONT_BOLD })
end

local function hint(text, visible)
  form.addRow(1)
  return form.addLabel({ label = text, font = FONT_MINI, visible = visible ~= false })
end

-- What monitoring still needs (FR-003); "" when complete.
local function missingText()
  local parts = {}
  if cfg.sId == 0 then
    parts[#parts + 1] = "RPM sensor"
  end
  if cfg.swCut == nil then
    parts[#parts + 1] = "Cut switch"
  end
  if cfg.idle == 0 then
    parts[#parts + 1] = "idle RPM"
  end
  if #parts == 0 then
    return ""
  end
  return "Needs: " .. table.concat(parts, ", ")
end

local function updateNeeds()
  if idx.needs then
    local text = missingText()
    form.setProperties(idx.needs, { label = text, visible = text ~= "" })
  end
end

-- A requirement changed: monitoring turns itself off if one is now missing.
local function onRequirementChanged()
  if cfg.en == 1 and missingText() ~= "" then
    save("en", 0)
    if idx.en then
      form.setValue(idx.en, false)
    end
  end
  recompute()
  updateNeeds()
end

-- Every sensor except date/time and GPS, as "Device / Label"; a saved sensor
-- that isn't present is shown as "<label> (not found)" (FR-022).
local function buildSensorList()
  sensorLabels, sensorIds, sensorPars, sensorUnits = { "(none)" }, { 0 }, { 0 }, { "" }
  notFoundIdx = 0
  local selected = 1
  local parent = ""
  for _, s in ipairs(system.getSensors()) do
    if s.param == 0 then
      parent = s.label
    elseif s.type ~= 5 and s.type ~= 9 then
      local n = #sensorLabels + 1
      sensorLabels[n] = (parent ~= "") and (parent .. " / " .. s.label) or s.label
      sensorIds[n], sensorPars[n], sensorUnits[n] = s.id, s.param, s.unit or ""
      if s.id == cfg.sId and s.param == cfg.sPar then
        selected = n
      end
    end
  end
  if cfg.sId ~= 0 and selected == 1 then
    notFoundIdx = #sensorLabels + 1
    sensorLabels[notFoundIdx] = cfg.sLbl .. " (not found)"
    sensorIds[notFoundIdx], sensorPars[notFoundIdx], sensorUnits[notFoundIdx] = cfg.sId, cfg.sPar, ""
    selected = notFoundIdx
  end
  return selected
end

-- Units that read as RPM (R9): "rpm", and "U/min" / "1/min" from German
-- converters, ignoring case.
local RPM_UNITS = { ["rpm"] = true, ["u/min"] = true, ["1/min"] = true }

-- Row 7 (FR-010): warn when the chosen sensor's unit isn't RPM-like.
local function updateUnitHint(i)
  if idx.unit then
    local u = sensorUnits[i] or ""
    local bad = i ~= 1 and i ~= notFoundIdx and not RPM_UNITS[string.lower(u)]
    form.setProperties(idx.unit, {
      label = "Unit is '" .. u .. "', not RPM. Check the sensor, or set Sensor scale.",
      visible = bad,
    })
  end
end

-- "= 31.5k" next to a threshold percentage.
local function kText(rpm)
  return string.format("= %.1fk RPM", rpm / 1000)
end

local function updateThresholdLabels()
  if idx.armK then
    form.setProperties(idx.armK, { label = kText(d.armRpm) })
  end
  if idx.flK then
    form.setProperties(idx.flK, { label = kText(d.flRpm) })
  end
  if idx.maxHint then
    local text = "0.0 = auto (4 x idle)"
    if cfg.maxR == 0 and d.idleRpm > 0 then
      text = text .. ": " .. string.format("%.1fk", d.fullRpm / 1000)
    end
    form.setProperties(idx.maxHint, { label = text })
  end
end

-- Live RPM row (FR-010), from loop() while the form is open, every 500 ms.
-- Reads the sensor itself: setup happens before monitoring is on.
local function updateLive(now)
  if not formOpen or not idx.live or now - st.liveAt < 500 then
    return
  end
  st.liveAt = now
  local text = TXT.noData
  if cfg.sId ~= 0 then
    local s = system.getSensorValueByID(cfg.sId, cfg.sPar)
    if s ~= nil and s.valid then
      text = fmtRpm(math.floor(s.value * d.kScale + 0.5))
    end
  end
  form.setProperties(idx.live, { label = text })
end

-- An intbox for a setting stored in tenths or hundreds, shown with 1 decimal.
local function addInt(label, key, step, after)
  form.addRow(2)
  form.addLabel({ label = label, width = LABEL_W })
  return form.addIntbox(cfg[key], RANGES[key][1], RANGES[key][2], DEFAULTS[key] --[[@as integer]], 1, step, function(value)
    save(key, value)
    recompute()
    if after then
      after()
    end
  end)
end

local function addCheck(label, key)
  form.addRow(2)
  form.addLabel({ label = label, width = LABEL_W })
  local i
  i = form.addCheckbox(cfg[key] == 1, function(value)
    local on = not value      -- the callback gets the old state
    if i then
      form.setValue(i, on)
    end
    save(key, on and 1 or 0)
  end)
end

local function initForm()
  formOpen = true

  heading(APP_NAME)
  form.addRow(2)
  form.addLabel({ label = "Monitoring", width = LABEL_W })
  idx.en = form.addCheckbox(cfg.en == 1, function(value)
    -- The callback gets the old state; toggle it (as in Speed Gauge).
    local on = not value
    if on and missingText() ~= "" then
      on = false              -- refused (FR-003); the hint says why
    end
    form.setValue(idx.en, on)
    save("en", on and 1 or 0)
    recompute()
    updateNeeds()
  end)
  idx.needs = hint("", false)

  if SIM then                 -- debug only (R12): pick a scripted RPM profile
    form.addRow(2)
    form.addLabel({ label = "SIM profile", width = 120 })
    form.addSelectbox(sim.names, sim.idx, false, function(i)
      sim.idx, sim.t0 = i, system.getTimeCounter()
      onCut()                 -- start each profile disarmed and silent
    end, { width = 200 })
  end

  heading("Engine")
  form.addRow(2)
  form.addLabel({ label = "RPM sensor", width = 120 })
  local selected = buildSensorList()
  form.addSelectbox(sensorLabels, selected, true, function(i)
    save("sId", sensorIds[i])
    save("sPar", sensorPars[i])
    if i == 1 then
      save("sLbl", "")
    elseif i ~= notFoundIdx then
      save("sLbl", string.sub(sensorLabels[i], 1, 63))
    end
    updateUnitHint(i)
    onRequirementChanged()
  end, { width = 200 })
  hint("No telemetry yet. The ECU must send RPM and the receiver", #sensorLabels == 1)
  hint("must be on. Some adapters take up to a minute.", #sensorLabels == 1)
  idx.unit = hint("", false)
  updateUnitHint(selected)

  form.addRow(2)
  form.addLabel({ label = "Sensor scale", width = LABEL_W })
  form.addSelectbox({ "x1", "x10", "x100", "x1000" }, cfg.scl, false, function(i)
    save("scl", i)
    recompute()
    st.liveAt = 0             -- show the rescaled value at once
  end)

  form.addRow(2)
  form.addLabel({ label = "Live RPM", width = LABEL_W })
  idx.live = form.addLabel({ label = TXT.noData, alignRight = true })

  local idxMax
  local function keepMax()    -- max RPM must stay above idle (FR-031b)
    if cfg.maxR ~= 0 and cfg.maxR <= cfg.idle then
      save("maxR", 0)
      recompute()
      if idxMax then
        form.setValue(idxMax, 0)
      end
    end
    updateThresholdLabels()
  end
  form.addRow(2)
  form.addLabel({ label = "Idle RPM (x1000)", width = LABEL_W })
  form.addIntbox(cfg.idle, RANGES.idle[1], RANGES.idle[2], 0, 1, 1, function(value)
    save("idle", value)
    onRequirementChanged()
    keepMax()
  end)
  hint("From the ECU setup. Check against Live RPM at idle.")

  form.addRow(2)
  form.addLabel({ label = "Max RPM (x1000)", width = LABEL_W })
  idxMax = form.addIntbox(cfg.maxR, RANGES.maxR[1], RANGES.maxR[2], 0, 1, 1, function(value)
    if value ~= 0 and value <= cfg.idle then
      if idxMax then
        form.setValue(idxMax, cfg.maxR) -- refused
      end
      form.setProperties(idx.maxHint, { label = "Max RPM must be above idle." })
      return
    end
    save("maxR", value)
    recompute()
    updateThresholdLabels()
  end)
  idx.maxHint = hint("")

  heading("Thresholds")
  local idxArm, idxFl
  local function refuse(box, old)
    if box then
      form.setValue(box, old)
    end
    form.setProperties(idx.thrHint, { visible = true })
  end
  form.addRow(2)
  form.addLabel({ label = "Arming at % of idle", width = LABEL_W })
  idxArm = form.addIntbox(cfg.armP, RANGES.armP[1], RANGES.armP[2], DEFAULTS.armP, 0, 1, function(value)
    if cfg.flP >= value then
      refuse(idxArm, cfg.armP)
      return
    end
    save("armP", value)
    recompute()
    updateThresholdLabels()
  end)
  idx.armK = hint("")
  form.addRow(2)
  form.addLabel({ label = "Flameout below % of idle", width = LABEL_W })
  idxFl = form.addIntbox(cfg.flP, RANGES.flP[1], RANGES.flP[2], DEFAULTS.flP, 0, 1, function(value)
    if value >= cfg.armP then
      refuse(idxFl, cfg.flP)
      return
    end
    save("flP", value)
    recompute()
    updateThresholdLabels()
  end)
  idx.flK = hint("")
  idx.thrHint = hint("Flameout must be below arming, and arming below idle.", false)

  addInt("Arming time (s)", "armT", 5)
  addInt("Detection delay (s)", "detT", 1)
  addInt("Telemetry loss after (s)", "lossT", 5)

  heading("Throttle cut")
  form.addRow(2)
  form.addLabel({ label = "Cut switch", width = LABEL_W })
  form.addInputbox(cfg.swCut, false, function(v)
    save("swCut", v)
    onRequirementChanged()
  end)
  hint("Assign with the switch in the Cut (engine off) position.")

  heading("Announcements")
  addCheck("Say \"armed\"", "sayArm")
  addCheck("Say \"relit\"", "sayRel")
  hint("Voice files missing: alarm uses beeps.", not audio.ok)

  form.addRow(1)
  form.addLabel({ label = APP_NAME .. " " .. APP_VERSION .. ". Advisory only; does not replace the ECU's failsafe.",
    font = FONT_MINI, alignRight = true })
  form.addRow(1)
  form.addLabel({ label = "Voice: Piper, Amy (CC BY-SA 4.0).", font = FONT_MINI, alignRight = true })

  updateNeeds()
  updateThresholdLabels()
  st.liveAt = 0
end

-- The form is gone: drop its indices so nothing calls form.* on them (R10).
local function closeForm()
  formOpen = false
  idx = {}
end

------------------------------------------------------------------------------
-- Telemetry window (contracts/telemetry-window.md). The only place lcd is used.
------------------------------------------------------------------------------

-- Window display state (data-model.md).
local function stateText()
  if st.testOn then
    return TXT.test
  elseif st.state == S.OFF then
    return TXT.off
  elseif not st.sensorFound then
    return TXT.noSensor
  elseif st.state == S.FLAMEOUT then
    return TXT.flameout
  elseif st.lost then
    return TXT.noTel
  elseif st.state == S.ARMED then
    return TXT.armed
  end
  return TXT.disarmed
end

-- Text layout: any window size, theme colors.
local function drawText(w)
  local r, g, b = lcd.getFgColor()
  lcd.setColor(r, g, b)
  if st.state == S.FLAMEOUT then
    lcd.drawText(4, 2, TXT.flameout, FONT_BIG)   -- dominant (FR-031)
    lcd.drawText(w - 4 - lcd.getTextWidth(FONT_MINI, st.rpmText), 24, st.rpmText, FONT_MINI)
    return
  end
  lcd.drawText(4, 2, stateText(), FONT_MINI)
  lcd.drawText(w - 4 - lcd.getTextWidth(FONT_NORMAL, st.rpmText), 2, st.rpmText, FONT_NORMAL)
end

local function printRpm(w, h)
  drawText(w)
end

------------------------------------------------------------------------------
-- Lifecycle
------------------------------------------------------------------------------

local function init()
  loadSettings()
  recompute()
  resetSession()
  checkAudio()                -- once: five file opens (R6)

  system.registerForm(1, MENU_APPS, APP_NAME, initForm, nil, nil, closeForm)
  system.registerTelemetry(1, APP_NAME, 0, printRpm)
end

local function loop()
  local now = system.getTimeCounter()
  if now - st.lastTick < TICK_MS then
    return
  end
  st.lastTick = now

  stepTest(now)               -- before the OFF check: tests work with monitoring off (R13)
  updateLive(now)             -- settings form's Live RPM row, also while OFF

  -- Row 0: off or not fully configured (FR-012, FR-034).
  if not d.active then
    if st.state == S.FLAMEOUT then
      stopAlarm()
    end
    st.state = S.OFF
    st.rpm = nil
    updateRpmText()
    return
  end
  if st.state == S.OFF then   -- just turned on
    st.state = S.DISARMED
    st.armSince, st.lowSince, st.invalidSince, st.lost = nil, nil, nil, false
  end

  -- Always call through system: Emulator Telemetry replaces it (R9).
  local s
  if SIM and sim.idx > 1 then
    s = simRead(now)
  else
    s = system.getSensorValueByID(cfg.sId, cfg.sPar)
  end
  local valid = false
  st.sensorFound = s ~= nil
  st.rpm = nil
  if s ~= nil and s.valid then
    valid = true
    st.rpm = s.value * d.kScale
  end

  -- Row 1: Cut wins over everything (FR-016). The RPM above is still read so
  -- the window follows the spool-down.
  if switchOn(cfg.swCut) then
    onCut()
    updateRpmText()
    return
  end

  if not valid then
    onInvalid(now)            -- row 2
  else
    st.invalidSince, st.lost = nil, false
    if st.state == S.DISARMED then
      stepDisarmed(now)
    elseif st.state == S.ARMED then
      stepArmed(now)
    elseif st.state == S.FLAMEOUT then
      stepFlameout(now)
    end
  end
  -- Valid or not: the alarm keeps cycling through a telemetry loss (FR-020a).
  if st.state == S.FLAMEOUT then
    stepCycle(now)
  end
  updateRpmText()
end

local function destroy()
  if st.state == S.FLAMEOUT or st.testOn then
    stopAlarm()
  end
end

---@type JetiApp
return {
  init = init,
  loop = loop,
  destroy = destroy,
  author = "Aaron George",
  version = APP_VERSION,
  name = APP_NAME,
}
