-- AG-FlmOt.lua — Flameout Alarm: turbine flameout alarm from RPM telemetry, with an RPM bar window.
-- Copyright (c) 2026 Aaron George
-- SPDX-License-Identifier: MIT
--
-- Listen-and-inform only: it reads one RPM sensor and two switches, plays
-- sound, vibrates the sticks and draws. It never controls the model or the
-- engine (constitution principle I). The sounds in /Apps/AG-FlmOt/ are
-- licensed CC BY-SA 4.0 (Piper "Amy" voice), not MIT (FR-028).
--
-- Design: specs/003-flameout-alarm/ (plan.md, research.md, data-model.md,
-- contracts/). Research decisions are cited as R1..R13.

local APP_NAME = "Flameout Alarm"
local APP_VERSION = "0.1.0"
local AUDIO_DIR = "/Apps/AG-FlmOt/"
local TICK_MS = 100         -- logic runs at most 10x per second (R8)
local CYCLE_MS = 5000       -- one alarm cycle, callout start to callout start (FR-023)
-- The JETI Studio emulator draws each window's title bar inside the reported
-- canvas (157 x 127 / 157 x 60, ~26 px hidden); the transmitter draws it
-- above and reports 150 x 68 / 150 x 23 (Speed Gauge, 2026-10-03).
local TITLE_H = 26

-- Sound files, generated by tools/voice/make_flameout.py (R5).
local SND = {
  cycle = AUDIO_DIR .. "cycle.wav",       -- "Flameout!" x3 + lock tone, 5.000 s
  cycletl = AUDIO_DIR .. "cycletl.wav",   -- the same with "Engine telemetry lost"
  tlost = AUDIO_DIR .. "tlost.wav",
  armed = AUDIO_DIR .. "armed.wav",
  relit = AUDIO_DIR .. "relit.wav",
}

-- Engine monitor states (data-model.md).
local S = { OFF = 0, DISARMED = 1, ARMED = 2, FLAMEOUT = 3 }

local TXT = {
  off = "OFF", noSensor = "NO SENSOR", noTel = "NO TELEMETRY", disarmed = "DISARMED",
  armed = "ARMED", flameout = "FLAMEOUT", test = "TEST", noData = "---",
}

-- Debug switches, both off for release (R11, R12).
local DEBUG_CPU = false     -- show per-call CPU on the double-size window
local SIM = false           -- replace the RPM sensor with scripted profiles

------------------------------------------------------------------------------
-- Settings (persisted per model; data-model.md). Integers, one string and
-- SwitchItems only; booleans as 0/1, times in 0.1 s, RPM in hundreds
-- (constitution IV).
------------------------------------------------------------------------------

local KEYS = {
  "en", "sId", "sPar", "sLbl", "scl", "swCut", "idle", "maxR", "armP", "flP",
  "armT", "detT", "lossT", "sayArm", "sayRel", "swTest", "cfgV",
}  -- 17 keys (limit 30)
local DEFAULTS = {
  en = 0, sId = 0, sPar = 0, sLbl = "", scl = 1, idle = 0, maxR = 0, armP = 90,
  flP = 70, armT = 30, detT = 10, lossT = 20, sayArm = 0, sayRel = 0, cfgV = 1,
}  -- swCut and swTest default to nil
local RANGES = {
  en = { 0, 1 }, scl = { 1, 4 }, idle = { 0, 1500 }, maxR = { 0, 3000 },
  armP = { 50, 98 }, flP = { 20, 95 }, armT = { 10, 100 }, detT = { 3, 50 },
  lossT = { 5, 100 }, sayArm = { 0, 1 }, sayRel = { 0, 1 },
}
local SCALES = { 1, 10, 100, 1000 }   -- sensor scale x1 .. x1000 (FR-006a)

local cfg = {}

local function save(key, value)
  cfg[key] = value
  system.pSave(key, value)
end

local function clamp(v, lo, hi)
  if v < lo then
    return lo
  elseif v > hi then
    return hi
  end
  return v
end

local function loadSettings()
  for _, key in ipairs(KEYS) do
    cfg[key] = system.pLoad(key, DEFAULTS[key])
  end
  for key, r in pairs(RANGES) do
    local v = clamp(cfg[key], r[1], r[2])
    if v ~= cfg[key] then
      save(key, v)
    end
  end
  -- Combinations the form never allows (data-model.md "Validation").
  if cfg.flP >= cfg.armP then
    save("armP", DEFAULTS.armP)
    save("flP", DEFAULTS.flP)
  end
  if cfg.maxR ~= 0 and cfg.maxR <= cfg.idle then
    save("maxR", 0)
  end
  if cfg.en == 1 and (cfg.sId == 0 or cfg.swCut == nil or cfg.idle == 0) then
    save("en", 0)
  end
end

------------------------------------------------------------------------------
-- Derived values: recomputed only when a setting changes, never per tick.
------------------------------------------------------------------------------

local d = {
  active = false,           -- monitoring on and fully configured (FR-003, FR-012)
  kScale = 1,               -- sensor value -> RPM
  idleRpm = 0, armRpm = 0, flRpm = 0, fullRpm = 1,
  armMs = 3000, detMs = 1000, lossMs = 2000,
}

local function recompute()
  d.active = cfg.en == 1 and cfg.sId ~= 0 and cfg.swCut ~= nil and cfg.idle > 0
  d.kScale = SCALES[cfg.scl]
  d.idleRpm = cfg.idle * 100
  d.armRpm = d.idleRpm * cfg.armP // 100
  d.flRpm = d.idleRpm * cfg.flP // 100
  if cfg.maxR ~= 0 then
    d.fullRpm = cfg.maxR * 100
  else
    d.fullRpm = math.max(1, 4 * d.idleRpm)
  end
  d.armMs = cfg.armT * 100
  d.detMs = cfg.detT * 100
  d.lossMs = cfg.lossT * 100
end

------------------------------------------------------------------------------
-- Session state (not persisted; reset by init on every model load).
------------------------------------------------------------------------------

local st = {}

local function resetSession()
  st.state = d.active and S.DISARMED or S.OFF
  st.rpm = nil              -- last valid RPM; nil while invalid
  st.sensorFound = true     -- false: the sensor isn't in the model's list (FR-022)
  st.invalidSince = nil
  st.lost = false           -- invalid for at least lossMs (NO TELEMETRY)
  st.armSince = nil         -- RPM >= armRpm since (DISARMED, FLAMEOUT)
  st.lowSince = nil         -- RPM < flRpm since (ARMED)
  st.cycleAt = 0            -- start of the current alarm cycle
  st.beepAt = nil           -- second fallback beep burst due (R6)
  st.tlPending = false      -- play cycletl.wav at the next cycle (R4)
  st.testOn = false         -- a test alarm is playing (R13)
  st.testPrev = true        -- a test switch already on at load needs a toggle
  st.rpmText = TXT.noData
  st.rpmHundreds = -1
  st.lastTick = system.getTimeCounter()
end

------------------------------------------------------------------------------
-- Audio (contracts/audio-events.md)
------------------------------------------------------------------------------

-- Which files exist, checked once in init() (R6).
local audio = { ok = false, tlost = false, armed = false, relit = false }

-- Jeti's io is function-style (constitution III).
local function fileExists(path)
  local f = io.open(path, "r")
  if f then
    io.close(f)
    return true
  end
  return false
end

local function checkAudio()
  audio.ok = fileExists(SND.cycle) and fileExists(SND.cycletl)
  audio.tlost = fileExists(SND.tlost)
  audio.armed = fileExists(SND.armed)
  audio.relit = fileExists(SND.relit)
end

-- Stops alarm sound at once, mid-callout or mid-beep (R3).
local function stopAlarm()
  system.stopPlayback(AUDIO_IMMEDIATE)
  st.beepAt = nil
  st.tlPending = false
end

------------------------------------------------------------------------------
-- Engine monitor (data-model.md "State transitions"). One function per row
-- group; each user story fills its own.
------------------------------------------------------------------------------

-- Unassigned switch = off. "On" is above half travel (R10).
local function switchOn(item)
  if item == nil then
    return false
  end
  local v = system.getInputsVal(item)
  return v ~= nil and v > 0.5
end

local function stepTest(now)            -- test alarm, rows T1-T3 (US8)
end

local function onCut(now)               -- row 1 (US2)
end

local function onInvalid(now)           -- row 2 (US6)
end

local function stepDisarmed(now)        -- row 3 (US1)
end

local function stepArmed(now)           -- row 4 (US1)
end

local function stepFlameout(now)       -- row 5 (US4)
end

local function stepCycle(now)           -- row 6 (US1)
end

-- "112,400" for the window, rebuilt only when RPM / 100 changes.
local function updateRpmText()
  local h = -1
  if st.rpm ~= nil then
    h = math.floor(st.rpm / 100 + 0.5)
  end
  if h == st.rpmHundreds then
    return
  end
  st.rpmHundreds = h
  if h < 0 then
    st.rpmText = TXT.noData
  elseif h >= 10 then
    st.rpmText = string.format("%d,%03d", h // 10, (h % 10) * 100)
  else
    st.rpmText = tostring(h * 100)
  end
end

------------------------------------------------------------------------------
-- Settings form (contracts/settings-form.md)
------------------------------------------------------------------------------

local sensorLabels, sensorIds, sensorPars = {}, {}, {}
local notFoundIdx = 0
local formOpen = false      -- loop may touch form rows only while true (R10)
local idx = {}              -- component indices of rows updated after creation

local LABEL_W = 210

local function heading(text)
  form.addRow(1)
  form.addLabel({ label = text, font = FONT_BOLD })
end

local function hint(text, visible)
  form.addRow(1)
  return form.addLabel({ label = text, font = FONT_MINI, visible = visible ~= false })
end

-- What monitoring still needs (FR-003); "" when complete.
local function missingText()
  local parts = {}
  if cfg.sId == 0 then
    parts[#parts + 1] = "RPM sensor"
  end
  if cfg.swCut == nil then
    parts[#parts + 1] = "Cut switch"
  end
  if cfg.idle == 0 then
    parts[#parts + 1] = "idle RPM"
  end
  if #parts == 0 then
    return ""
  end
  return "Needs: " .. table.concat(parts, ", ")
end

local function updateNeeds()
  if idx.needs then
    local text = missingText()
    form.setProperties(idx.needs, { label = text, visible = text ~= "" })
  end
end

-- A requirement changed: monitoring turns itself off if one is now missing.
local function onRequirementChanged()
  if cfg.en == 1 and missingText() ~= "" then
    save("en", 0)
    if idx.en then
      form.setValue(idx.en, false)
    end
  end
  recompute()
  updateNeeds()
end

-- Every sensor except date/time and GPS, as "Device / Label"; a saved sensor
-- that isn't present is shown as "<label> (not found)" (FR-022).
local function buildSensorList()
  sensorLabels, sensorIds, sensorPars = { "(none)" }, { 0 }, { 0 }
  notFoundIdx = 0
  local selected = 1
  local parent = ""
  for _, s in ipairs(system.getSensors()) do
    if s.param == 0 then
      parent = s.label
    elseif s.type ~= 5 and s.type ~= 9 then
      local n = #sensorLabels + 1
      sensorLabels[n] = (parent ~= "") and (parent .. " / " .. s.label) or s.label
      sensorIds[n], sensorPars[n] = s.id, s.param
      if s.id == cfg.sId and s.param == cfg.sPar then
        selected = n
      end
    end
  end
  if cfg.sId ~= 0 and selected == 1 then
    notFoundIdx = #sensorLabels + 1
    sensorLabels[notFoundIdx] = cfg.sLbl .. " (not found)"
    sensorIds[notFoundIdx], sensorPars[notFoundIdx] = cfg.sId, cfg.sPar
    selected = notFoundIdx
  end
  return selected
end

local function initForm()
  formOpen = true

  heading(APP_NAME)
  form.addRow(2)
  form.addLabel({ label = "Monitoring", width = LABEL_W })
  idx.en = form.addCheckbox(cfg.en == 1, function(value)
    -- The callback gets the old state; toggle it (as in Speed Gauge).
    local on = not value
    if on and missingText() ~= "" then
      on = false              -- refused (FR-003); the hint says why
    end
    form.setValue(idx.en, on)
    save("en", on and 1 or 0)
    recompute()
    updateNeeds()
  end)
  idx.needs = hint("", false)

  heading("Engine")
  form.addRow(2)
  form.addLabel({ label = "RPM sensor", width = 120 })
  local selected = buildSensorList()
  form.addSelectbox(sensorLabels, selected, true, function(i)
    save("sId", sensorIds[i])
    save("sPar", sensorPars[i])
    if i == 1 then
      save("sLbl", "")
    elseif i ~= notFoundIdx then
      save("sLbl", string.sub(sensorLabels[i], 1, 63))
    end
    onRequirementChanged()
  end, { width = 200 })

  form.addRow(2)
  form.addLabel({ label = "Idle RPM (x1000)", width = LABEL_W })
  form.addIntbox(cfg.idle, RANGES.idle[1], RANGES.idle[2], 0, 1, 1, function(value)
    save("idle", value)
    onRequirementChanged()
  end)
  hint("From the ECU setup. Check against Live RPM at idle.")

  heading("Throttle cut")
  form.addRow(2)
  form.addLabel({ label = "Cut switch", width = LABEL_W })
  form.addInputbox(cfg.swCut, false, function(v)
    save("swCut", v)
    onRequirementChanged()
  end)
  hint("Assign with the switch in the Cut (engine off) position.")

  form.addRow(1)
  form.addLabel({ label = APP_NAME .. " " .. APP_VERSION .. ". Advisory only; does not replace the ECU's failsafe.",
    font = FONT_MINI, alignRight = true })

  updateNeeds()
end

-- The form is gone: drop its indices so nothing calls form.* on them (R10).
local function closeForm()
  formOpen = false
  idx = {}
end

------------------------------------------------------------------------------
-- Telemetry window (contracts/telemetry-window.md). The only place lcd is used.
------------------------------------------------------------------------------

-- Window display state (data-model.md).
local function stateText()
  if st.testOn then
    return TXT.test
  elseif st.state == S.OFF then
    return TXT.off
  elseif not st.sensorFound then
    return TXT.noSensor
  elseif st.state == S.FLAMEOUT then
    return TXT.flameout
  elseif st.lost then
    return TXT.noTel
  elseif st.state == S.ARMED then
    return TXT.armed
  end
  return TXT.disarmed
end

-- Text layout: any window size, theme colors.
local function drawText(w)
  local r, g, b = lcd.getFgColor()
  lcd.setColor(r, g, b)
  lcd.drawText(4, 2, stateText(), FONT_MINI)
  lcd.drawText(w - 4 - lcd.getTextWidth(FONT_NORMAL, st.rpmText), 2, st.rpmText, FONT_NORMAL)
end

local function printRpm(w, h)
  drawText(w)
end

------------------------------------------------------------------------------
-- Lifecycle
------------------------------------------------------------------------------

local function init()
  loadSettings()
  recompute()
  resetSession()
  checkAudio()                -- once: five file opens (R6)

  system.registerForm(1, MENU_APPS, APP_NAME, initForm, nil, nil, closeForm)
  system.registerTelemetry(1, APP_NAME, 0, printRpm)
end

local function loop()
  local now = system.getTimeCounter()
  if now - st.lastTick < TICK_MS then
    return
  end
  st.lastTick = now

  stepTest(now)               -- before the OFF check: tests work with monitoring off (R13)

  -- Row 0: off or not fully configured (FR-012, FR-034).
  if not d.active then
    if st.state == S.FLAMEOUT then
      stopAlarm()
    end
    st.state = S.OFF
    st.rpm = nil
    updateRpmText()
    return
  end
  if st.state == S.OFF then   -- just turned on
    st.state = S.DISARMED
    st.armSince, st.lowSince, st.invalidSince, st.lost = nil, nil, nil, false
  end

  -- Row 1: Cut wins over everything (FR-016).
  if switchOn(cfg.swCut) then
    onCut(now)
    return
  end

  -- Always call through system: Emulator Telemetry replaces it (R9).
  local s = system.getSensorValueByID(cfg.sId, cfg.sPar)
  if s == nil or not s.valid then
    st.sensorFound = s ~= nil
    st.rpm = nil
    onInvalid(now)            -- row 2
  else
    st.sensorFound = true
    st.rpm = s.value * d.kScale
    st.invalidSince, st.lost = nil, false
    if st.state == S.DISARMED then
      stepDisarmed(now)
    elseif st.state == S.ARMED then
      stepArmed(now)
    elseif st.state == S.FLAMEOUT then
      stepFlameout(now)
    end
  end
  -- Valid or not: the alarm keeps cycling through a telemetry loss (FR-020a).
  if st.state == S.FLAMEOUT then
    stepCycle(now)
  end
  updateRpmText()
end

local function destroy()
  if st.state == S.FLAMEOUT or st.testOn then
    stopAlarm()
  end
end

---@type JetiApp
return {
  init = init,
  loop = loop,
  destroy = destroy,
  author = "Aaron George",
  version = APP_VERSION,
  name = APP_NAME,
}
