"""make_voice.py - generate Speed Gauge's app voice (Piper "Amy").

Copyright (c) 2026 Aaron George
SPDX-License-Identifier: MIT

Writes 512 WAV files (numbers 0-500, unit and warning phrases) plus
CREDITS.txt and index.txt to src/Apps/AG-SpdGa/voice/. The files are not
committed (spec FR-035); see tools/voice/README.md and research R13 in
specs/001-speed-gauge/research.md.

    python tools/voice/make_voice.py --model <path>/en_US-amy-medium.onnx

Exits 1 if a file is missing or a number-only file up to 199 is longer
than 1.3 s (SC-009).
"""

import argparse
import io
import sys
import wave
from array import array
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO / "src" / "Apps" / "AG-SpdGa" / "voice"

MAX_NUM = 500
PHRASES = [  # (file stem, text): FR-030
    ("mph", "miles per hour"),
    ("kmh", "kilometers per hour"),
    ("kt", "knots"),
    ("ms", "meters per second"),
    ("fts", "feet per second"),
    ("pct", "percent"),
    ("stall", "stall warning"),
    ("over", "overspeed"),
    ("alive", "airspeed alive"),
    ("stallat", "stall warning at"),
    ("cal", "airspeed calibration"),
    ("max", "max"),              # max-speed callout (FR-019a, 2026-10-04)
]
EXPECTED = MAX_NUM + 1 + len(PHRASES)  # 513

SILENCE = 184         # |sample| below this is silence: about -45 dBFS
PAD_S = 0.020         # silence kept at each end so words don't clip
PEAK = 29205          # common peak level: -1 dBFS
SHORT_MAX = 199       # number-only callouts up to this ...
SHORT_LIMIT_S = 1.3   # ... must fit in this (SC-009)

ONES = ["zero", "one", "two", "three", "four", "five", "six", "seven",
        "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen",
        "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"]
TENS = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy",
        "eighty", "ninety"]

CREDITS = """Speed Gauge (AG-SpdGa) - app voice
==================================

The WAV files in this folder were generated by tools/voice/make_voice.py
in the jeti-lua-apps repository. They are licensed CC BY-SA 4.0 (below),
not MIT like the rest of the repository.

Speech synthesis: Piper, https://github.com/rhasspy/piper (MIT), as
packaged by piper-tts, https://github.com/OHF-Voice/piper1-gpl
(GPL-3.0-or-later). Only used to generate these files; no Piper code is
included here.

Voice: "Amy" (en_US-amy-medium), by Mycroft / Rhasspy,
https://huggingface.co/rhasspy/piper-voices, licensed under
Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0),
https://creativecommons.org/licenses/by-sa/4.0/

These generated files are distributed under CC BY-SA 4.0. They were
trimmed of silence, peak-normalized and, if needed, resampled.
"""


def number_words(n: int) -> str:
    """US English without "and": 112 -> "one hundred twelve"."""
    if n < 20:
        return ONES[n]
    if n < 100:
        tens, ones = divmod(n, 10)
        return TENS[tens] + ("" if ones == 0 else " " + ONES[ones])
    hundreds, rest = divmod(n, 100)
    words = ONES[hundreds] + " hundred"
    return words if rest == 0 else words + " " + number_words(rest)


def phrase_list() -> list:
    return [(str(n), number_words(n)) for n in range(MAX_NUM + 1)] + PHRASES


def synthesize(voice, syn_config, text: str):
    """Returns (mono 16-bit samples, sample rate)."""
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        voice.synthesize_wav(text, w, syn_config=syn_config)
    with wave.open(io.BytesIO(buf.getvalue()), "rb") as r:
        if r.getsampwidth() != 2:
            raise RuntimeError(f"expected 16-bit audio, got {8 * r.getsampwidth()}-bit")
        channels, rate = r.getnchannels(), r.getframerate()
        data = array("h", r.readframes(r.getnframes()))
    if sys.byteorder == "big":
        data.byteswap()
    if channels > 1:
        data = data[::channels]
    return data, rate


def trim(samples: array, rate: int) -> array:
    loud = [i for i, s in enumerate(samples) if abs(s) >= SILENCE]
    if not loud:
        return samples
    pad = int(PAD_S * rate)
    return samples[max(0, loud[0] - pad):min(len(samples), loud[-1] + 1 + pad)]


def normalize(samples: array) -> array:
    peak = max((abs(s) for s in samples), default=0)
    if peak == 0:
        return samples
    k = PEAK / peak
    return array("h", (max(-32768, min(32767, round(s * k))) for s in samples))


def resample(samples: array, src: int, dst: int) -> array:
    """Linear interpolation; good enough for speech going up in rate."""
    if src == dst or len(samples) < 2:
        return samples
    n = max(1, round(len(samples) * dst / src))
    last = len(samples) - 1
    out = array("h", bytes(2 * n))
    for i in range(n):
        pos = i * src / dst
        j = min(int(pos), last - 1)
        f = pos - j
        out[i] = round(samples[j] * (1 - f) + samples[j + 1] * f)
    return out


def write_wav(path: Path, samples: array, rate: int) -> None:
    data = array("h", samples)
    if sys.byteorder == "big":
        data.byteswap()
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(data.tobytes())


def write_text(path: Path, text: str) -> None:
    """UTF-8 with LF line endings (Path.write_text has no newline= before 3.10)."""
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def duration(path: Path) -> float:
    with wave.open(str(path), "rb") as r:
        return r.getnframes() / r.getframerate()


def self_check(out: Path) -> int:
    missing = [stem for stem, _ in phrase_list() if not (out / f"{stem}.wav").is_file()]
    if missing:
        print(f"FAIL: {len(missing)} file(s) missing, e.g. {', '.join(missing[:5])}")
        return 1
    longest, which = max((duration(out / f"{n}.wav"), n) for n in range(SHORT_MAX + 1))
    print(f"{EXPECTED} files present. Longest number up to {SHORT_MAX}: "
          f"{which} ({number_words(which)}), {longest:.2f} s")
    if longest > SHORT_LIMIT_S:
        print(f"FAIL: over {SHORT_LIMIT_S} s (SC-009). Try a higher --speed")
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Speed Gauge's app voice.")
    ap.add_argument("--model", required=True, type=Path,
                    help="path to en_US-amy-medium.onnx (its .onnx.json next to it)")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help="output folder (default: src/Apps/AG-SpdGa/voice)")
    ap.add_argument("--rate", type=int, choices=(16000, 22050, 44100), default=22050,
                    help="output sample rate (default 22050, Amy's own)")
    ap.add_argument("--speed", type=float, default=1.5,
                    help="speaking speed relative to Piper's own pace (default 1.5: fits SC-009's 1.3 s)")
    ap.add_argument("--missing", action="store_true",
                    help="only synthesize files that don't exist yet (keeps the rest unchanged)")
    args = ap.parse_args()

    if not args.model.is_file():
        print(f"Model not found: {args.model}")
        return 1
    try:
        from piper import PiperVoice
        try:
            from piper import SynthesisConfig
        except ImportError:
            from piper.config import SynthesisConfig
    except ImportError:
        print("piper-tts is not installed: python -m pip install -r tools/voice/requirements.txt")
        return 1

    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=True)
    index = out / "index.txt"
    if index.exists():
        index.unlink()  # written last, so its presence marks a complete run

    voice = PiperVoice.load(str(args.model))
    syn_config = SynthesisConfig(length_scale=1.0 / args.speed)
    phrases = phrase_list()
    for k, (stem, text) in enumerate(phrases, 1):
        if args.missing and (out / f"{stem}.wav").is_file():
            continue
        samples, rate = synthesize(voice, syn_config, text)
        samples = normalize(trim(samples, rate))
        write_wav(out / f"{stem}.wav", resample(samples, rate, args.rate), args.rate)
        if k % 50 == 0 or k == len(phrases):
            print(f"{k}/{len(phrases)}")

    write_text(out / "CREDITS.txt", CREDITS)
    write_text(index, f"voice=en_US-amy-medium\nrate={args.rate}\nspeed={args.speed}\n"
                      f"files={EXPECTED}\n")
    return self_check(out)


if __name__ == "__main__":
    sys.exit(main())
