"""make_flameout.py - generate Flameout Alarm's sounds (Piper "Amy").

Copyright (c) 2026 Aaron George
SPDX-License-Identifier: MIT

Writes five WAV files plus CREDITS.txt to src/Apps/AG-FlmOt/ (spec 003,
FR-026 to FR-028; research R5 in specs/003-flameout-alarm/research.md):

    cycle.wav     urgent "Flameout!" x3, then the lock tone, exactly 5.000 s
    cycletl.wav   the same with "Engine telemetry lost" after the callout
    tlost.wav     "Engine telemetry lost"
    armed.wav     "Flameout alarm armed"
    relit.wav     "Engine relit"

    python tools/voice/make_flameout.py --model <path>/en_US-amy-medium.onnx

Reuses make_voice.py's helpers (Speed Gauge's generator) without changing
it. Exits 1 if a file is missing or a length check fails.
"""

import argparse
import math
import sys
import wave
from array import array
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from make_voice import (PEAK, normalize, resample, synthesize, trim,  # noqa: E402
                        write_text, write_wav)

REPO = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO / "src" / "Apps" / "AG-FlmOt"

CYCLE_S = 5.0            # one alarm cycle, callout start to callout start (FR-023)
CALLOUT_MAX_S = 2.5      # "about 2 s" (FR-023)
CYCLETL_VOICE_MAX_S = 4.0  # leaves at least 1 s of lock tone (R5)
REPEAT_GAP_S = 0.12      # between the three "Flameout!"
TL_GAP_S = 0.15          # between the callout and "Engine telemetry lost"

# Urgent delivery (R5): the draft's Piper length scale 0.70, then ffmpeg
# asetrate x1.07 + atempo 0.9346. Same result without a time-stretch:
# synthesize 7% slower, then play 7% faster (pitch up about a semitone).
PITCH = 1.07
URGENT_LENGTH = 0.70 * PITCH
URGENT_NOISE = 0.5
HPF_HZ = 150.0
PRESENCE_HZ, PRESENCE_DB, PRESENCE_Q = 3000.0, 4.0, 1.0
COMP_THRESH_DB, COMP_RATIO = -18.0, 4.0
COMP_ATTACK_S, COMP_RELEASE_S, COMP_MAKEUP_DB = 0.003, 0.060, 4.0

CALM_SPEED = 1.5         # Speed Gauge's pace, for the non-alarm phrases

# Lock tone, from the approved sample (2026-10-02, FR-027).
TONE_HZ, OVERTONE_HZ, OVERTONE_LEVEL = 1800.0, 3600.0, 0.3
BEEP_ON_S, BEEP_OFF_S, BEEP_FADE_S = 0.045, 0.035, 0.003

CALM = [("tlost", "Engine telemetry lost"),
        ("armed", "Flameout alarm armed"),
        ("relit", "Engine relit")]
FILES = ["cycle", "cycletl"] + [stem for stem, _ in CALM]

CREDITS = """Flameout Alarm (AG-FlmOt) - alarm sounds
========================================

The WAV files in this folder were generated by tools/voice/make_flameout.py
in the jeti-lua-apps repository. They are licensed CC BY-SA 4.0 (below),
not MIT like the rest of the repository.

Speech synthesis: Piper, https://github.com/rhasspy/piper (MIT), as
packaged by piper-tts, https://github.com/OHF-Voice/piper1-gpl
(GPL-3.0-or-later). Only used to generate these files; no Piper code is
included here.

Voice: "Amy" (en_US-amy-medium), by Mycroft / Rhasspy,
https://huggingface.co/rhasspy/piper-voices, licensed under
Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0),
https://creativecommons.org/licenses/by-sa/4.0/

The lock tone is synthesized by the script and contains no voice.

These generated files are distributed under CC BY-SA 4.0. The speech was
sped up, pitch-shifted, equalized, compressed, trimmed of silence and
peak-normalized.
"""


# --- Filters (RBJ audio EQ cookbook) ----------------------------------------

def biquad(x: list, b0, b1, b2, a0, a1, a2) -> list:
    b0, b1, b2, a1, a2 = b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0
    y = [0.0] * len(x)
    x1 = x2 = y1 = y2 = 0.0
    for i, v in enumerate(x):
        out = b0 * v + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2
        x2, x1, y2, y1 = x1, v, y1, out
        y[i] = out
    return y


def high_pass(x: list, rate: int, f0: float, q: float = 0.7071) -> list:
    w0 = 2 * math.pi * f0 / rate
    c, alpha = math.cos(w0), math.sin(w0) / (2 * q)
    return biquad(x, (1 + c) / 2, -(1 + c), (1 + c) / 2, 1 + alpha, -2 * c, 1 - alpha)


def peaking(x: list, rate: int, f0: float, gain_db: float, q: float) -> list:
    a = 10 ** (gain_db / 40)
    w0 = 2 * math.pi * f0 / rate
    c, alpha = math.cos(w0), math.sin(w0) / (2 * q)
    return biquad(x, 1 + alpha * a, -2 * c, 1 - alpha * a, 1 + alpha / a, -2 * c, 1 - alpha / a)


def compress(x: list, rate: int) -> list:
    """Peak envelope follower, hard knee."""
    att = math.exp(-1 / (COMP_ATTACK_S * rate))
    rel = math.exp(-1 / (COMP_RELEASE_S * rate))
    env, out = 0.0, [0.0] * len(x)
    for i, v in enumerate(x):
        a = abs(v)
        k = att if a > env else rel
        env = k * env + (1 - k) * a
        level = 20 * math.log10(max(env, 1e-9) / 32768)
        over = level - COMP_THRESH_DB
        gain_db = COMP_MAKEUP_DB - (over * (1 - 1 / COMP_RATIO) if over > 0 else 0)
        out[i] = v * 10 ** (gain_db / 20)
    return out


def to_int16(x: list) -> array:
    return array("h", (max(-32768, min(32767, round(v))) for v in x))


# --- Sounds --------------------------------------------------------------------

def silence(seconds: float, rate: int) -> array:
    return array("h", bytes(2 * round(seconds * rate)))


def urgent(voice, cfg_cls, text: str, out_rate: int) -> array:
    samples, rate = synthesize(voice, cfg_cls(length_scale=URGENT_LENGTH,
                                              noise_scale=URGENT_NOISE), text)
    samples = resample(samples, round(rate * PITCH), rate)   # asetrate x1.07
    x = [float(s) for s in samples]
    x = high_pass(x, rate, HPF_HZ)
    x = peaking(x, rate, PRESENCE_HZ, PRESENCE_DB, PRESENCE_Q)
    x = compress(x, rate)
    return resample(normalize(trim(to_int16(x), rate)), rate, out_rate)


def calm(voice, cfg_cls, text: str, out_rate: int) -> array:
    samples, rate = synthesize(voice, cfg_cls(length_scale=1.0 / CALM_SPEED), text)
    return resample(normalize(trim(samples, rate)), rate, out_rate)


def lock_tone(n: int, rate: int) -> array:
    """n samples of the beep pattern, faded out at the end if cut mid-beep."""
    on, period = round(BEEP_ON_S * rate), round((BEEP_ON_S + BEEP_OFF_S) * rate)
    fade = max(1, round(BEEP_FADE_S * rate))
    scale = PEAK / (1 + OVERTONE_LEVEL)
    out = array("h", bytes(2 * n))
    for i in range(n):
        j = i % period
        if j >= on:
            continue
        t = j / rate
        env = min(1.0, j / fade, (on - j) / fade, (n - i) / fade)
        v = math.sin(2 * math.pi * TONE_HZ * t) + OVERTONE_LEVEL * math.sin(2 * math.pi * OVERTONE_HZ * t)
        out[i] = round(scale * env * v)
    return out


def cycle(voice_part: array, rate: int) -> array:
    total = round(CYCLE_S * rate)
    if len(voice_part) >= total:
        raise RuntimeError("voice part is longer than the cycle")
    return voice_part + lock_tone(total - len(voice_part), rate)


# --- Check -----------------------------------------------------------------------

def duration(path: Path) -> float:
    with wave.open(str(path), "rb") as r:
        return r.getnframes() / r.getframerate()


def self_check(out: Path, rate: int, callout_s: float, tl_voice_s: float) -> int:
    ok = True
    missing = [f for f in FILES if not (out / f"{f}.wav").is_file()]
    if missing:
        print(f"FAIL: missing {', '.join(missing)}")
        return 1
    for f in ("cycle", "cycletl"):
        with wave.open(str(out / f"{f}.wav"), "rb") as r:
            n = r.getnframes()
        if n != round(CYCLE_S * rate):
            print(f"FAIL: {f}.wav is {n} samples, expected {round(CYCLE_S * rate)}")
            ok = False
    print(f"Callout: {callout_s:.2f} s (max {CALLOUT_MAX_S}). "
          f"cycletl voice: {tl_voice_s:.2f} s (max {CYCLETL_VOICE_MAX_S}).")
    if callout_s > CALLOUT_MAX_S or tl_voice_s > CYCLETL_VOICE_MAX_S:
        print("FAIL: voice part too long for the 5-second cycle")
        ok = False
    for stem, _ in CALM:
        print(f"{stem}.wav: {duration(out / f'{stem}.wav'):.2f} s")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Flameout Alarm's sounds.")
    ap.add_argument("--model", required=True, type=Path,
                    help="path to en_US-amy-medium.onnx (its .onnx.json next to it)")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help="output folder (default: src/Apps/AG-FlmOt)")
    ap.add_argument("--rate", type=int, choices=(16000, 22050, 44100), default=22050,
                    help="output sample rate (default 22050, Amy's own)")
    args = ap.parse_args()

    if not args.model.is_file():
        print(f"Model not found: {args.model}")
        return 1
    try:
        from piper import PiperVoice
        try:
            from piper import SynthesisConfig
        except ImportError:
            from piper.config import SynthesisConfig
    except ImportError:
        print("piper-tts is not installed: python -m pip install -r tools/voice/requirements.txt")
        return 1

    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=True)
    rate = args.rate
    voice = PiperVoice.load(str(args.model))

    word = urgent(voice, SynthesisConfig, "Flameout!", rate)
    gap = silence(REPEAT_GAP_S, rate)
    callout = word + gap + word + gap + word
    phrases = {stem: calm(voice, SynthesisConfig, text, rate) for stem, text in CALM}
    tl_voice = callout + silence(TL_GAP_S, rate) + phrases["tlost"]

    write_wav(out / "cycle.wav", cycle(callout, rate), rate)
    write_wav(out / "cycletl.wav", cycle(tl_voice, rate), rate)
    for stem, samples in phrases.items():
        write_wav(out / f"{stem}.wav", samples, rate)
    write_text(out / "CREDITS.txt", CREDITS)
    return self_check(out, rate, len(callout) / rate, len(tl_voice) / rate)


if __name__ == "__main__":
    sys.exit(main())
